### ISSUE TITLE
docker部署方式

### ISSUE THREAD

**Issue by yuntian123456** [renhai-lab/sgcc_electricity#16]
大佬，有没有类似这种简单的部署方式，一个命令行就搞定的

docker run --name sgcc_electricity -d -e PHONE_NUMBER="" -e PASSWORD="" -e HASS_URL="" -e HASS_TOKEN="" --restart unless-stopped sgcc/electricity:1.0_

**Comment by renhai-lab** [comment]
暂时没有，可以用别人的[仓库](https://github.com/liantianji/sgcc_electricity)通过上述命令行部署。
PS：docker-compose方式部署更容易维护，是docker推荐的部署方式
