### ISSUE TITLE
Webdriver quit abnormly

### ISSUE THREAD

**Issue by lenhoo** [renhai-lab/sgcc_electricity#19]
一直报错
`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".user"}
  (Session info: headless chrome=90.0.4430.212)`
参考 #1 修改了时间也没用

**Comment by renhai-lab** [comment]
参考 #18 更换账号，升级docker镜像试试

**Comment by renhai-lab** [comment]
还有其他报错吗？

**Comment by lenhoo** [comment]
是我的网络问题，已解决，非常感谢！
