### ISSUE TITLE
docker方式部署，配置文件正常，build后容器不停重启

### ISSUE THREAD

**Issue by dajokeer** [renhai-lab/sgcc_electricity#23]
<img width="1185" alt="image" src="https://github.com/renhai-lab/sgcc_electricity/assets/10276819/93b4b0fe-4655-4419-b071-23a1e26bf65a">

**Comment by renhai-lab** [comment]
设置env环境中的`LOG_LEVEL="DUBUG"` ，再看看有没有其他的日志输出

**Comment by dajokeer** [comment]
上面已经设置成 DEBUG了
对了 如果是 DUBUG，会报错

**Comment by renhai-lab** [comment]
是的，我打错了，是DEBUG。

如果没有其他日志信息，很难判断问题出在哪。

**Comment by ABUAIJUTIE** [comment]
同样的问题，在QNAP上部署，尝试了 docker compose，也用 Portainer 创建 Stack，都是无限重启，LOG_LEVEL 设置了 DEBUG，但输出还是 INFO。
唯一可以看到的是这个：
`sgcc_electricity exited with code 132`

**Comment by renhai-lab** [comment]
您的Docker容器退出并返回了错误代码132，这通常是由于以下原因之一：

1. **架构不匹配**：您可能正在尝试在不支持的CPU架构上运行镜像。例如，尝试在ARM架构上运行为x86_64构建的镜像。

2. **旧的CPU指令集**：某些镜像可能需要较新的CPU指令集。如果您的CPU较老，可能不支持这些指令集。

为了解决此问题，您可以尝试以下操作：

1. **检查CPU架构**：确保您的Docker容器镜像与您的CPU架构相匹配。您可以使用`uname -m`命令查看您的机器的架构。

2. **查找专门为您的架构构建的镜像**：例如，如果您正在ARM架构上运行，尝试查找为ARM构建的Docker镜像。

3. **更新Docker和操作系统**：确保您的Docker版本和操作系统都是最新的。

4. **查看容器日志**：使用`docker logs <container_id_or_name>`查看容器的日志，这可能会给您提供更多关于问题的信息。

5. **使用不同的镜像版本**：尝试使用旧的或不同的镜像版本，看看是否可以解决问题。

如果上述建议都不能解决问题，建议您查看Docker的官方文档或社区论坛，看看是否有其他用户遇到了相同的问题。
