### ISSUE TITLE
加入自定义实体以后，显示未知

### ISSUE THREAD

**Issue by huhubeibei** [renhai-lab/sgcc_electricity#8]
大佬，我在后台安装以后，后台已经显示获取了数据，但是加入实体以后，显示未知，能给看看么？

**Comment by renhaiidea** [comment]
重启homeassistant试试

**Comment by huhubeibei** [comment]
已经试过了，不行，对代码之类的完全是小白，废了好大劲才安上的，大佬空了可以给看看不，wx:78679635

**Comment by renhaiidea** [comment]
你直接把相关截图发来看看

**Comment by huhubeibei** [comment]
![image](https://github.com/renhaiidea/sgcc_electricity/assets/76635939/46daadbb-3624-4204-a0b5-965e44b3ed8f)
![image](https://github.com/renhaiidea/sgcc_electricity/assets/76635939/7c9cf80b-0db1-4d4e-b4af-7d5200b4840a)
![image](https://github.com/renhaiidea/sgcc_electricity/assets/76635939/23f051b1-3e6e-4653-a0b5-fe0b6491f878)
![image](https://github.com/renhaiidea/sgcc_electricity/assets/76635939/0d9561ff-8ad9-4c7d-a878-11e9959d876c)

**Comment by huhubeibei** [comment]
![image](https://github.com/renhaiidea/sgcc_electricity/assets/76635939/d6c6f937-f1e8-4fe5-b836-5868a5bb86e7)

**Comment by renhaiidea** [comment]
先重启此docker容器试试，命令行输入
`docker restart sgcc_electricity `，查看后台的sensor更新是否成功

**Comment by huhubeibei** [comment]
![image](https://github.com/renhaiidea/sgcc_electricity/assets/76635939/13d0bb07-f36b-4bb1-a9fd-1be0c108f926)

**Comment by renhaiidea** [comment]
现在实体应该有数据了

**Comment by huhubeibei** [comment]
![image](https://github.com/renhaiidea/sgcc_electricity/assets/76635939/11256c14-f37b-4dba-958b-cebf8450e12d)

**Comment by renhaiidea** [comment]
“疑难杂症”，电量获取和更新传感器没出错，错误可能出现在homeassistant这边，暂时不知道问题在哪

**Comment by huhubeibei** [comment]
大佬晚上可以给远程看看么？

**Comment by renhaiidea** [comment]
现在帮不了，homeassistant这块我也不是很懂。你可以不自定义实体，也就是删掉template中那四个试试能不能用。

**Comment by renhaiidea** [comment]
你可以把你的homeassistant的版本等相关信息贴在这，看看有没有人知道为什么。

**Comment by huhubeibei** [comment]
![image](https://github.com/renhaiidea/sgcc_electricity/assets/76635939/2647287b-fe03-4e1e-97eb-0b4fb7284078)
templatebu'ding不定义实体的话，查询不到更没法用吧？

**Comment by huhubeibei** [comment]
![image](https://github.com/renhaiidea/sgcc_electricity/assets/76635939/f7050d8d-34e7-4212-8666-32291d14e506)
