### ISSUE TITLE
如果能开发addon版本就好了

### ISSUE THREAD

**Issue by lxgxdx** [renhai-lab/sgcc_electricity#9]
目前是配置成功了，haos运行在unraid虚拟机中，本程序跑在unraid的docker中，但是ha重启之后相关数据就会丢失，需要再次重启docker，毕竟这个docker正常每天只获取一次数据，不能做到ha重启自动重新获取数据。大佬研究一下开发开发吧，原版的我也搭建了，但是不知道是我有多个户号还是别的什么原因，一直报错。

**Comment by renhaiidea** [comment]
正常情况数据不会丢失，会被记录在home assistant的数据库里。
add-on有空会开发。

**Comment by renhai-lab** [comment]
和 #3 一样
